apiVersion: v1
kind: Service
metadata:
  name: api-{{ .Release.Name }}-0
  labels:
    {{- include "client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    {{- include "client.selectorLabels" . | nindent 4 }}
